### ISSUE TITLE
Wrong evaluation of lambda expression

### ISSUE THREAD

**Issue by jbescos** [jakartaee/expression-language#257]
In version 3.0.4, running the next expression, that is not a LambdaExpression, `#{(tReadOnly)}` fails with:
```
Caused by: com.sun.el.parser.ParseException: Encountered "}" at line 1, column 14.
Was expecting:
    "->" ...
    
	at com.sun.el.parser.ELParser.generateParseException(ELParser.java:3715)
	at com.sun.el.parser.ELParser.jj_consume_token(ELParser.java:3574)
	at com.sun.el.parser.ELParser.LambdaExpression(ELParser.java:371)
	at com.sun.el.parser.ELParser.Assignment(ELParser.java:290)
	at com.sun.el.parser.ELParser.SemiColon(ELParser.java:235)
	at com.sun.el.parser.ELParser.Expression(ELParser.java:228)
	at com.sun.el.parser.ELParser.DeferredExpression(ELParser.java:144)
	at com.sun.el.parser.ELParser.CompositeExpression(ELParser.java:57)
	at com.sun.el.lang.ExpressionBuilder.createNodeInternal(ExpressionBuilder.java:146)
	... 5 more
```

It works when the expression is `#{tReadOnly}`.

Find here a reproducer:

```
public class Main {

    private static final String WORK_EXPRESION = "#{tReadOnly}";
    private static final String NOT_WORK_EXPRESION = "#{(tReadOnly)}";
    
    public static void main(String[] args) {
        execute(WORK_EXPRESION);
        execute(NOT_WORK_EXPRESION);
    }

    private static void execute(String expression) {
        ExpressionFactory factory = new ExpressionFactoryImpl();
        StandardELContext context = new StandardELContext(factory);
        context.getVariableMapper().setVariable("tReadOnly",
            factory.createValueExpression(true, Boolean.class));
        ValueExpression valueExpression = factory.createValueExpression(context, expression, Boolean.class);
        Object result = valueExpression.getValue(context);
        System.out.println("Expression Result: " + result);
    }
}
```

Output is:
```
Expression Result: true
Exception in thread "main" javax.el.ELException: Error Parsing: #{(tReadOnly)}
	at com.sun.el.lang.ExpressionBuilder.createNodeInternal(ExpressionBuilder.java:176)
	at com.sun.el.lang.ExpressionBuilder.build(ExpressionBuilder.java:198)
	at com.sun.el.lang.ExpressionBuilder.createValueExpression(ExpressionBuilder.java:249)
	at com.sun.el.ExpressionFactoryImpl.createValueExpression(ExpressionFactoryImpl.java:86)
	at Main.execute(Main.java:22)
	at Main.main(Main.java:14)
Caused by: com.sun.el.parser.ParseException: Encountered "}" at line 1, column 14.
Was expecting:
    "->" ...
    
	at com.sun.el.parser.ELParser.generateParseException(ELParser.java:3715)
	at com.sun.el.parser.ELParser.jj_consume_token(ELParser.java:3574)
	at com.sun.el.parser.ELParser.LambdaExpression(ELParser.java:371)
	at com.sun.el.parser.ELParser.Assignment(ELParser.java:290)
	at com.sun.el.parser.ELParser.SemiColon(ELParser.java:235)
	at com.sun.el.parser.ELParser.Expression(ELParser.java:228)
	at com.sun.el.parser.ELParser.DeferredExpression(ELParser.java:144)
	at com.sun.el.parser.ELParser.CompositeExpression(ELParser.java:57)
	at com.sun.el.lang.ExpressionBuilder.createNodeInternal(ExpressionBuilder.java:146)
	... 5 more

```

**Comment by markt-asf** [comment]
This is an issue in the implementation rather than the API and the implementation has been moved to https://github.com/eclipse-ee4j/expressly

I'm going to close this but feel free to re-open it if Expressly decide not to support that far back. I'm not saying we'll fix it if they won't - a 3.0.x implementation release from this project seems very unlikely - but we can at least take a further look.

Note: There are Java EE 8 EL implementations that don't have this issue (I've just tested Tomcat's) so that is another option.

**Comment by jbescos** [comment]
OK, @markt-asf  I will create and issue there. The reason I opened here is that for version 3.X the code is in this repo.

**Comment by jbescos** [comment]
I am reopening it because I created a PR in this repo.
